### ISSUE TITLE
 usar variáveis do css. 

### ISSUE THREAD

**Issue by JCDMeira** [viniciuslemos93/consumindo-api-filmes#1]
Porque ao usar variáveis do css a informação de cores é centralizado em um lugar só, e se precisar mudar, se muda em um lugar só. Respeitando o princípio "One source of truth"

**Comment by viniciuslemos93** [comment]
Boa!!, como  nesse projeto foquei mais no consumo de API, acabou que não fiz as variáveis do CSS, bem lembrado!!
